/** The fixed set of vendor categories — used as a picklist at vendor signup
 * and as the category multi-select when browsing/searching vendors, so both
 * screens share one source of truth. */
export const VENDOR_CATEGORIES = [
  "Event Management Company",
  "Photography and Videography Services",
  "Marriage hall and Banquet Hall",
  "Food / Chef",
  "Gift and Event hamper",
  "Flower decorations",
  "Grooming Services",
  "Light Decorator",
  "Mandap Decorator / Tenthouse",
  "Outdoor Catering Services",
  "Furniture Rental",
  "Singer and Musical band",
  "Small Event Venue",
  "DJ and Sound system",
  "Special Effects",
  "Stay and Hotels",
  "Marriage Garments",
  "Hotel and Resorts",
  "Influencer",
  "Invitation Cards",
  "Live Streaming Services",
  "Party plots",
  "Ballon Decorator",
  "Transportation",
  "Clothes on rent",
  "Honeymoon Planner",
  "Jewelers",
  "Mehendi Artist",
  "Generator",
  "Pandit",
  "Ritual Material Services",
] as const;
