/** The fixed set of vendor categories — used as a picklist at vendor signup
 * and as the category multi-select when browsing/searching vendors, so both
 * screens share one source of truth. */
export const VENDOR_CATEGORIES = [
  "Ballon Decorator",
  "Clothes on rent",
  "DJ and Sound system",
  "Event Management Company",
  "Flower decorations",
  "Food / Chef",
  "Furniture Rental",
  "Generator",
  "Gift and Event hamper",
  "Grooming Services",
  "Honeymoon Planner",
  "Hotel and Resorts",
  "Influencer",
  "Invitation Cards",
  "Jewelers",
  "Light Decorator",
  "Live Streaming Services",
  "Mandap Decorator / Tenthouse",
  "Marriage Garments",
  "Marriage hall and Banquet Hall",
  "Mehendi Artist",
  "Outdoor Catering Services",
  "Pandit",
  "Party plots",
  "Photography and Videography Services",
  "Ritual Material Services",
  "Singer and Musical band",
  "Small Event Venue",
  "Special Effects",
  "Stay and Hotels",
  "Transportation",
] as const;
